# Data-X IEOR 290 : HW 2
## Ankit Dutta
### SID: 3032167048

In [1]:
#Importing Numpy as np
import numpy as np


Problem 1: Numpy

1

In [2]:
#Creating numpy arrays a and b

a=np.arange(10,20,1)
print(a)

b=np.linspace(1,7,10)
print(b)

[10 11 12 13 14 15 16 17 18 19]
[ 1.          1.66666667  2.33333333  3.          3.66666667  4.33333333
  5.          5.66666667  6.33333333  7.        ]


In [3]:
#1.1
#Squaring all elements in both arrays and storing them into a new element 
asq= a**2
print(asq)
bsq=b**2
print(bsq)

[100 121 144 169 196 225 256 289 324 361]
[  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]


In [4]:
#1.2
#Summing up the array
sq=asq+bsq
print(sq)

[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]


In [5]:
#1.3
#Summing every even elements (index) starting at 0
sum(sq[::2])

1105.0

In [6]:
#1.4
#Square root of all elements of the added array
np.sqrt(sq)

array([ 10.04987562,  11.12554618,  12.22474721,  13.34166406,
        14.47219556,  15.61338457,  16.76305461,  17.91957341,
        19.08169571,  20.24845673])

2

In [7]:
#Appending b to a and reshaping it to a 5x4
m=np.append(a,b).reshape(5,4)
print(m)

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


3

In [8]:
#Creating a matrix m2 extracting 2nd,3rd columns from m
m2=m[:,1:3]
print(m2)

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


4

In [9]:
#Creating a dot product for the transpose of matrix m2 and m
m3=np.dot(np.transpose(m2),m)
print(m3)

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


5

In [10]:
#Rounding up the matrix m3 to 2 decimal places
m3=np.around(m3,decimals=2)
print(m3)

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


6 

In [11]:
#Sorting the m3 array such that the highest value is at the top left
np.sort(m3.flatten())[::-1].reshape(2,4)

array([[ 748.11,  697.33,  489.89,  482.33],
       [ 454.56,  437.89,  437.89,  402.22]])